### ISSUE TITLE
兼容 django 4.0

### ISSUE THREAD

**Issue by chenluyong** [pavlov99/json-rpc#123]
### Description

`cannot import name 'url' from 'django.conf.urls'`

### Steps to Reproduce

depends django version is 4.0

### [Informacje o wydaniu Django 4.0](https://docs.djangoproject.com/pl/4.0/releases/4.0/#features-removed-in-4-0)

`django.conf.urls.url() is removed.` [more](https://docs.djangoproject.com/pl/3.2/ref/urls/#url)

### solution

use `re_path`  [more](https://docs.djangoproject.com/pl/3.2/ref/urls/#re-path)

`from django.conf.urls import url` to `from django.urls import re_path` 

and replace the relevant reference function.

**Comment by pavlov99** [comment]
@chenluyong does `re_path` work the same as `url`? Do you know if a patch
```
try:
    from django.conf.urls import url
except:
    from django.urls import re_path as url
```
work? (I have not worked with Django past v2, not sure about the current design).

**Comment by MattFisher** [comment]
@pavlov99 since Django 2.0, [django.conf.urls.url()](https://docs.djangoproject.com/en/3.2/ref/urls/#url) has been an alias of [django.urls.re_path()](https://docs.djangoproject.com/en/3.2/ref/urls/#django.urls.re_path) for backwards compatibility.
