### ISSUE TITLE
dispatcher class methods

### ISSUE THREAD

**Issue by crazylime** [pavlov99/json-rpc#24]
If I use a class to hold the dispatcher methods and decorate them with @dispatcher.add_method
I always get "Invalid params"  code: -32602.

I have to add a parameter 'self':None to the request to get this to work.

Thank you

**Comment by pavlov99** [comment]
@crazylime let me check it.

**Comment by pavlov99** [comment]
@crazylime , could you provide code example? Does this help https://github.com/pavlov99/json-rpc/blob/master/jsonrpc/tests/test_dispatcher.py#L63-73 ?

**Comment by crazylime** [comment]
Hi

Passing in the class to the Dispatcher constructor works perfectly.

Thank you

**Comment by pavlov99** [comment]
You are welcome! Happy library usage!
