### ISSUE TITLE
Customizing the dispatcher for the Flask back end is difficult.

### ISSUE THREAD

**Issue by jashug** [pavlov99/json-rpc#33]
Since `Dispatcher` acts as a collection, it evaluates as `False` when empty. This causes the assignment `self.dispatcher = dispatcher or Dispatcher()` to make a new `Dispatcher` instance when passed an empty `Dispatcher`.

To reproduce:
```
class SubDispatcher(Dispatcher):
    pass

type(JSONRPCAPI(SubDispatcher()).dispatcher) == Dispatcher # This should be SubDispatcher
```

**Comment by pavlov99** [comment]
@jashug , custom dispatcher functionality was implemented and new version of the package released: https://pypi.python.org/pypi/json-rpc/1.10.2

**Comment by jashug** [comment]
Thanks for the update. That fixed my problem.

**Comment by jashug** [comment]
I'm using this in https://github.com/hashplex/Lightning, specifically `jsonrpcproxy.py`.
