### ISSUE TITLE
client example

### ISSUE THREAD

**Issue by csselo** [pavlov99/json-rpc#38]
Hi

I want to test ur server with advanced rest client
but some param is wrong

what must I write in raw payload panel?

thanks

**Comment by csselo** [comment]
I copied ur payload but nothing change
parse error

like
{
        "method": "add",
        "params": [1, 2],
        "jsonrpc": "2.0",
        "id": 1,
    }

**Comment by csselo** [comment]
it works :) when I erase blanks

**Comment by pavlov99** [comment]
Great!
