### ISSUE TITLE
HTTPS w/TLS support

### ISSUE THREAD

**Issue by rtubio** [pavlov99/json-rpc#44]
Dear all,

Does this library support establishing connections to a JSON-RPC server over HTTPS?

I am currently using RPC4Django that implements a JSON-RPC interface over HTTPS (externally handled by Apache).

Thanks, Ricardo.

**Comment by pavlov99** [comment]
Dear Ricardo,

This library does not depend on http/https protocol, it is purely transport implementation. Let me address your questions in details.

1. If the use-case is to connect to json-rpc server, than there is no point to use any "json-rpc-like" library. Python requests would do the job. Even though this library supports client connection, I personally think it is overhead to use "json-rpc" for client side.
If use-case is to implement json-rpc server, this library would be helpful.

2. In terms of protocol usage, "json-rpc" does not limit developers to any of them. One may possible to use it with http/https (Django/Tornado etc.) as well as message queue servers (RabbitMQ+pika). As a benefit, it does not require developer to choose specific framework.

As I understood from your question, Django works as a web server on tcp port, https connections are proxied via Apache. In this case https implementation is purely on Apache side, while Django does not know anything about it (well, except settings, such as secure cookie handler).

This library would handle this case, in fact optional Django connector would simplify views development. Please refer to the documentation for more information: https://json-rpc.readthedocs.org/en/latest/django_integration.html

**Comment by rtubio** [comment]
Thanks @pavlov99 , that answers my question for sure.
