### ISSUE TITLE
Variable number of args and kwargs for handler functions

### ISSUE THREAD

**Issue by michaelimfeld** [pavlov99/json-rpc#52]
Hi

I couldn't find anything about this in the docs:
Does this library support a variable number of args **and** kwargs for a handler function?

Example:
```python
@dispatcher.add_method
def foobar(*args, **kwargs):
    return kwargs["foo"] + kwargs["bar"] + args[0]
```

**Comment by pavlov99** [comment]
@michaelimfeld it does support a variable number of arguments, however, with slightly different approach. JSON-RPC standard allows arguments of the function to be sent either as list or dictionary, but not as a mix of them. This library follows the standard and does not allow both `*args` and `**kwargs` at the same time. There is a workaround in your case, `args` could be extra key of `kwargs`:

```python
@dispatcher.add_method
def foobar(**kwargs):
    return kwargs["foo"] + kwargs["bar"] + kwargs["args"][0]
```

Payload in this case would have `params` value:

```json
{"foo": 1, "bar": 2, "args": [3]}
```

Does it work?

**Comment by michaelimfeld** [comment]
Yes, works!
