### ISSUE TITLE
Support multiple callbacks

### ISSUE THREAD

**Issue by Naatan** [pavlov99/json-rpc#55]
At the moment there is no way of specifying whether a response is final or if there are more responses, meaning JSON-RPC only supports a single response for each request. This means it does not cover use-cases where the server sends response data as it comes in, rather than having to wait for all the response data to complete and then send it. Think for an example of a search engine that uses JSON-RPC.

I suggest simply adding a field called `complete` which indicates whether this is the last response for the given request id.

**Comment by pavlov99** [comment]
Yes, correct, there is no such case. And I would argue whether it is good to implement such architecture. If you would like to receive multiple responses as they are generated, then it is server-side push message. It would not help to keep a connection with the server and wait for the "final" response. I believe, that web-sockets could help to address the issue. What do you think about it?

**Comment by pavlov99** [comment]
No further feedback. Closing the issue.
