### ISSUE TITLE
Client API?

### ISSUE THREAD

**Issue by mikepurvis** [pavlov99/json-rpc#57]
Would this package consider supplying a client API similar to [this one](https://github.com/gerold-penz/python-jsonrpc#http-client-example)?

If the `getaddr` tricks give people the willies, an alternative might be to explicitly initialize each remote method, for example:

```
from jsonrpc import Remote

# Optional kwargs for jsonrpc, headers
my_remote = Remote(url)
my_remote.add_method('echo')
my_remote.add_method('ping', notify=True)

response = my_remote.echo('foobar')
print response.result

my_remote.ping()  # returns None
```

**Comment by pavlov99** [comment]
Hi, @mikepurvis 

It is possible, in fact, this package has response parsing functionality already. In terms of client implementation, I'm a bit skeptical: 

* First of all, it should be transport related (http/rabbitmq/etc.), which was not initially designed (transport agnostic library)
* Second, client implementation is relatively simple and might not worth it to be in the library.

Both points are arguable and I'm not against the client implementation. Based on my experience it is usually implemented in JavaScript and Python implementation might not be popular. Let's consider an example:

```python
class Remote(object):
    def __init__(self, url):
        self.url = url

    def call(self, method, params):
        payload = {
            "method": method,
            "params": params,
            "jsonrpc": "2.0",
            "id": 0,
        }

        response = requests.post(self.url, data=json.dumps(payload), headers=headers).json()
        return response

my_remote = Remote(url)

# Instead of
# my_remote.add_method('echo')
# response = my_remote.echo('foobar')
my_remote.call('echo', 'foobar')
```

The interface here is very similar to one, you proposed.
@mikepurvis what do you think about it and what are your possible use cases?

Cheers.

**Comment by mikepurvis** [comment]
Thanks for the response! My particular use case is a background management daemon which exposes a jsonrpc service that a CLI tool is able to interact with in order to command/query the daemon. Both parts of this system are written in Python.

I didn't realise there was [a result class already present here](https://github.com/pavlov99/json-rpc/blob/5605dc50fa495841315f28266ef80d0692e70d18/jsonrpc/jsonrpc2.py#L167); will investigate further.

Another implementation possibility would be doing proxies on a function-by-function basis, so that a user can build up their own Remote object, eg:

```
class MyRemote(object):
    def __init__(self, url):
        r = Remote(url, version='2.0')
        self.echo = r.method('echo')
        self.ping = r.method('ping')

m = MyRemote(my_url)
m.echo('foobar')
```

In any case, as you say, the client side is fairly simple. I'll play around with it in my project, and if I come to something that seems it may be worth contributing upstream, I'll wake this up.
