### ISSUE TITLE
question: use it with flask to a demo,but the requested url not found.

### ISSUE THREAD

**Issue by Scofieldsu** [pavlov99/json-rpc#60]
> run.py

```
from flask import Flask

from jsonrpc.backend.flask import api

app = Flask(__name__)
app.register_blueprint(api.as_blueprint())
app.add_url_rule('/', 'api', api.as_view())

@api.dispatcher.add_method
def my_method(*args, **kwargs):
    return args, kwargs

if __name__ == '__main__':
    app.run(debug=True)
```
- - - 
then i use postman to  post the url : localhost:5000/api/

data:{
    "jsonrpc": "2.0",
    "id": "1111",
    "method": "my_method",
    "params": ["1"]
  }
- - - 
response  404 
- - - 
help~

**Comment by pavlov99** [comment]
@Scofieldsu should not it be a call to `localhost:5000` instead? Seems you create api endpoint within `/` path: `app.add_url_rule('/', 'api', api.as_view())`

**Comment by Scofieldsu** [comment]
@pavlov99 thank u!! i  misunderstand add_url_rule('/', 'api', api.as_view())~~i want to use this json-rpc to do  webapi test page  . similar to flask-jsonrpc 's  /api/browse, but it depends on flask.

**Comment by pavlov99** [comment]
Seems solution has been found. Nothing to fix.
