### ISSUE TITLE
License file in pypi archive

### ISSUE THREAD

**Issue by toddrme2178** [pavlov99/json-rpc#90]
The pypi source archive isn't including the `LICENSE.txt` file. Would it be possible to add it? It is very helpful when packaging this for Linux distributions. Thank you.

**Comment by toddrme2178** [comment]
[simplejson](https://pypi.org/project/simplejson/) has it.  There is a list of top python packages [here](https://pythonwheels.com/), and pretty much all the top ones have a license file in the source archive.

It is also a requirement of the license itself:

> The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

And it is recommended by the [upstream python packaging guidelines](https://packaging.python.org/guides/distributing-packages-using-setuptools/#license-txt).

**Comment by pavlov99** [comment]
Hi, @toddrme2178 
Thank you for your suggestion again. `json-rpc` has a LICENSE file in `dist/` from [1.11.1 version](https://pypi.org/project/json-rpc/).

**Comment by pavlov99** [comment]
By the way, if you would be packaging this for Linux distributions, may you include the link here?

**Comment by toddrme2178** [comment]
It is for [openSUSE](http://opensuse.org).  It is already available in openSUSE's rolling Tumbleweed release and should be in the next non-rolling Leap release.
