### ISSUE TITLE
Uart as a transport layer

### ISSUE THREAD

**Issue by ahmadwaqaskhilji** [pavlov99/json-rpc#92]
Hi,

Is is possible to use the json-rpc with uart as a transporter. Do you have any example where transport layer and protocol are separated.

Thank you

**Comment by pavlov99** [comment]
Hi, @ahmadwaqaskhilji 

Are you referring to [this](https://en.wikipedia.org/wiki/Universal_asynchronous_receiver-transmitter) uart? Please provide a link to it.

Transport/protocol separation is following:

* Protocol is responsible for a message format, e.g. it defines JSON object with `method` and `args`. This is what `json-rpc` library does, it is not aware of how you transfer the message.
* Transport is a way to pass your message to the server and back. It could be either API call (with Django, Flask, Asyncio, etc.) or you could communicate via messaging queue (RabbitMQ, Kafka).
