### ISSUE TITLE
`make env` fails without requirements-dev.txt

### ISSUE THREAD

**Issue by adeadman** [pavlov99/json-rpc#97]
### Description
When setting up a test development environment, the included Makefile has a target `env` that should create a virtual environment and install the development dependencies. However, the `make env` command fails because `requirements-dev.txt` is not present in the repository.

### Steps to Reproduce

1. `git clone` the repository
2. Change to the repository directory
3. run `make env`

**Expected behavior:** The environment is installed and ready for development and testing

**Actual behavior:** The virtualenv is created, but pip fails to install dependencies with error `Could not open requirements file: [Errno 2] No such file or directory: 'requirements-dev.txt'`

**Reproduces how often:** all the time

### Versions

Not applicable

### Additional Information

This is on branch `master`, but it may be present in other branches.

**Comment by pavlov99** [comment]
@adeadman thank you for the issue report.

Historically Makefile was used as a set of shortcuts, `make test` or `make env` are some of them.

As this project aims to support multiple python environments, it uses `tox` as the main environment manager and this is preferred way compared to `make env`. To avoid confusions, I've removed `make env` and `make test` commands. `tox -e <ENV>` should be used instead.

Hope this resolves the issue.
